#!/bin/bash
set -e

PATH=/home/rgabriana/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Root check 

if [ $UID != 0 ]; then 

  echo -e "YOU NEED ADMIN PRIVELEGES TO RUN THIS SCRIPT\n"
  exit

else
 
  echo -e "The purpose of this script is to extract the raspberry pi image and mount the image so that you can modify it.\n"

fi

read -p "Please enter the file location of the raspberry pi image? " rimage


# Image check 

if [ ! -e $rimage ]; then

  echo -e "$rimage file is not a regular file\n"
  exit

fi

if [ ! -r $rimage ]; then 

  echo -e "You don't have permission to read $rimage . \n"
  exit

fi

# dir check 

echo -e "Raspberry pi's comes with 2 partitions.\nA root partition and a boot partition.\n"
read -p "Please enter the folder you want to mount the root partition? " rmount

# root

if [ ! -d $rmount ]; then 

  mkdir -pv $rmount

fi

read -p "Please enter the folder you want to mount the boot partition? " bmount

# boot

if [ ! -d $bmount ]; then

  mkdir -pv $bmount

fi

echo -e "One moment please while I mount those partitions\n"

# partition calculation

rdisksize=`fdisk -l $rimage|grep -e '.img2'|grep -v grep|awk -F " " '{print $2}'`
roffset=`echo $[rdisksize*512]`
bdisksize=`fdisk -l $rimage|grep -e '.img1'|grep -v grep|awk -F " " '{print $2}'`
boffset=`echo $[bdisksize*512]`

# mount the first partition

mount -v -t vfat -o loop,offset=$boffset $rimage $bmount

# mount the second partition

mount -v -t ext4 -o loop,offset=$roffset $rimage $rmount

echo -e "Your raspberry pi boot image has been mounted to \n $bmount \n and your root image \
has been mounted to \n $rmount.\nThis script can also apply your modified configs onto the \
image, for this to work properly, the directory structure of the \"source\" folders and files \
must match the targets folders and files.\n Example: \"/source/direcotry/path/file\" -> \
\"$rmount/directory/path/file\".\n"

read -p "Do you want to load your modified configs into this raspberry pi image? " mod

  case $mod in

    [Yy][Ee][Ss] )

      read -p "enter the full path of the modified configs: " config_folder
      configs=$(find $config_folder -type f)

      for src in $configs; do
        target_folder=$rmount/`dirname $src | sed -s "s|$config_folder||"`
        target_file=`basename $src`
        file_check () {
          md5sum $1 | awk -F " " '{print $1}'
	}
        [ ! -d $target_folder ] && echo -e "creating target folders" && mkdir -pv $target_folder

          if [ $(file_check $target_folder/$target_file) !=  $(file_check $src) ]; then
            echo -e "creating backups of $target_file"
            cp -pv $target_folder/$target_file $target_folder/$target_file.bk
            echo -e "implementing modified configs"
            cp -pv $src $target_folder
            chown --reference=$target_folder/$target_file.bk $target_folder/$target_file
            chmod --reference=$target_folder/$target_file.bk $target_folder/$target_file
          else
            echo -e "$target_folder/$target_file and $src are the same no actions needed"
          fi

      done

      mount_ () {
      read -p "Load complete do you want to unmount? " umount
      case $umount in 

        [Yy][Ee][Ss] )
          umount -v $rmount
          umount -v $bmount
          exit
        ;;

        [Nn][Oo] )
          echo -e "As you wish"
          exit
        ;;

        * )
          echo -e "Please answer yes or no"
          mount_
        ;;

      esac }

      mount_
    ;;

    [Nn][Oo] )

      echo -e "As you wish.  Goodday\n"
      exit
    ;;

    * )

      echo -e "I really do not have time to pander your indecissiveness.  Goodbye\n"
      exit
    ;;

  esac
