#!/usr/bin/perl -w 
use strict;
use Data::Dumper;
use SOAP::Lite;# +trace => ['debug'];
use POSIX;

my $JASPER_URI = 'http://api.jasperwireless.com/ws/schema';
my $WSSE_URI = 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd';
my $PASSWORD_TYPE = 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText';

my $env = 'api';
my $url = 'https://'.$env.'.jasperwireless.com/ws/service/terminal';
my $soapAction = 'http://api.jasperwireless.com/ws/service/terminal/EditTerminal';
my $licenseKey = 'a988d4de-210c-4691-8ede-1defe19d5ff4';
my $userName = 'devops';
my $password = '1qaz!QAZ2wsx2wsx';

my $service = SOAP::Lite->proxy($url)->uri($JASPER_URI)->autotype(0)->readable(1);
$service->on_fault(sub {
    my ($soap,$response) = @_;
    die('The following SOAP fault occurred:', "\n",
	' faultcode: ', $response->faultcode(), "\n",
	' faultstring: ', $response->faultstring(), "\n",
	' faultdetail: ', Dumper($response->faultdetail()), "\n")
    });

$service->on_action(sub{return $soapAction;});
my $result = $service->call('EditTerminalRequest' => (
  SOAP::Header->uri($WSSE_URI)->name('wsse:Security' =>
      \SOAP::Data->name('wsse:UsernameToken'=>
          \SOAP::Data->value(
	      SOAP::Data->name('wsse:Username' => $userName),
	      SOAP::Data->name('wsse:Password' => $password)->
		   attr({Type => $PASSWORD_TYPE})))),
  SOAP::Data->name('messageId' => ''),
  SOAP::Data->name('version' => ''),
  SOAP::Data->name('licenseKey' => $licenseKey),
  SOAP::Data->name('iccid' => "$ARGV[0]"),
  SOAP::Data->name('targetValue' => "$ARGV[1]"),
  SOAP::Data->name('changeType' => '6')
));

#print "Call result:\n" . Dumper($result);
#->valueof('//sessionInfo/session/dateSessionStarted'));
